Bugfix/fancontrol on old aurora
dudanov/MideaUART pull request #9
Opened 2023-08-05 21:09 UTC by andrasbiro

These were the fixes needed to support my msabbu-12hrdn1 (I think about 5 years old Aurora), what I used with EU-OSK103 dongle so far.

The first commit resolves that the AC's status report is shorter than what the code expects, e.g.:
RX: AA 1E AC 00 00 00 00 00 00 03 C0 01 AA 66 7F 7F 00 00 00 00 00 66 5E 00 00 00 00 00 00 6D 33 
This is 19B long, so m_getFreezeProtection() overreads it, resulting MideUART thinking the AC is in freeze protection mode and denying control of the fan. 

The second one resolves that the AC reports 30/50 for LOW/MEDIUM, instead of 40/60. This was also reported here:
https://github.com/esphome/issues/issues/2528

I've tested it with esphome 2023.7.1

2023-08-06 10:20 UTC, dudanov requested changes

2023-08-06 10:20 UTC, dudanov commented on src/Appliance/AirConditioner/StatusData.cpp
> +}
```suggestion
  const uint8_t fanMode = this->m_getValue(3);
  if (fanMode == 30) {
    fanMode = FAN_LOW;
  } else if (fanMode == 50) {
    fanMode = FAN_MEDIUM;
  }
  return static_cast<FanMode>(fanMode); 
}
```

2023-08-06 10:20 UTC, dudanov commented on src/Frame/FrameData.cpp
> +}
```suggestion
uint8_t FrameData::m_getValue(uint8_t idx, uint8_t mask, uint8_t shift) const {
  if (idx < this->m_data.size())
    return (this->m_data[idx] >> shift) & mask;
  return 0;
}
```

2023-08-07 04:17 UTC, merged

2023-08-07 04:17 UTC, dudanov commented
Thanks!

2023-08-07 06:58 UTC, andrasbiro commented
Thank you for the great project! I was able to get rid of that annoying mide app :)